export const HTTP_METHOD = Object.freeze({
  GET: 'GET',
  POST: 'POST',
  DELETE: 'DELETE',
  PUT: 'PUT',
  PATCH: 'PATCH',
});

export const EMOJI = Object.freeze({
  API: {
    EMOJI: '/emojis',
    CATEGORY: '/categories',
  },
  CATEGORY: {
    'smileys-emotion': '감정',
    'people-body': '사람',
    'animals-nature': '동물 및 자연',
    'food-drink': '음식',
    'travel-places': '장소',
    activities: '활동',
    objects: '사물',
    symbols: '기호',
    flags: '플래그',
  },
  SUB_CATEGORY: [
    'face-smiling',
    'face-affection',
    'face-tongue',
    'face-hand',
    'face-neutral-skeptical',
    'face-sleepy',
    'face-unwell',
    'face-hat',
    'face-glasses',
    'face-concerned',
    'face-negative',
    'face-costume',
    'cat-face',
    'monkey-face',
    'emotion',
    'hand-fingers-open',
    'hand-fingers-partial',
    'hand-single-finger',
    'hand-fingers-closed',
    'hands',
    'hand-prop',
    'body-parts',
    'person',
    'person-gesture',
    'person-role',
    'person-fantasy',
    'person-activity',
    'person-sport',
    'person-resting',
    'family',
    'person-symbol',
    'skin-tone',
    'hair-style',
    'animal-mammal',
    'animal-bird',
    'animal-amphibian',
    'animal-reptile',
    'animal-marine',
    'animal-bug',
    'plant-flower',
    'plant-other',
    'food-fruit',
    'food-vegetable',
    'food-prepared',
    'food-asian',
    'food-marine',
    'food-sweet',
    'drink',
    'dishware',
    'place-map',
    'place-geographic',
    'place-building',
    'place-religious',
    'place-other',
    'transport-ground',
    'transport-water',
    'transport-air',
    'hotel',
    'time',
    'sky-weather',
    'event',
    'award-medal',
    'sport',
    'game',
    'arts-crafts',
    'clothing',
    'sound',
    'music',
    'musical-instrument',
    'phone',
    'computer',
    'light-video',
    'book-paper',
    'money',
    'mail',
    'writing',
    'office',
    'lock',
    'tool',
    'science',
    'medical',
    'household',
    'other-object',
    'transport-sign',
    'warning',
    'arrow',
    'religion',
    'zodiac',
    'av-symbol',
    'gender',
    'math',
    'punctuation',
    'currency',
    'other-symbol',
    'keycap',
    'alphanum',
    'geometric',
    'flag',
    'country-flag',
    'subdivision-flag',
  ],
});
